### ISSUE TITLE
Ich habe ein Problem

### ISSUE THREAD

**Issue by Wertzui123** [Hyroxing/TeamTools#5]
Also 1. man darf ja die plugin.yml net ändern, versteh ich ja auch, aber die API Version ist veraltert, somit kann ich dein Plugin leider nicht benutzen... Und 2. würde ich gerne die Command Beschreibungen ändern. Also darf ich die plugin.yml anpassen? @Hyroxing-Development

**Comment by iTzFreeHD** [comment]
Ja du darfst die API-Version natürlich ändern

**Comment by Wertzui123** [comment]
Ok, danke

**Comment by Wertzui123** [comment]
Und Command Beschreibungen? Keine Sorge, ich lass dich als Autor etc.

**Comment by TobiasG-DE** [comment]
Diese darfst du ebenfalls verändern

**Comment by Wertzui123** [comment]
Super danke
